### ISSUE TITLE
Port to firefox

### ISSUE THREAD

**Issue by heubergen** [lobbylayer/chrome#1]
As Firefox support more and more WebExtensions API are supported, this addon should be easy to port it to FF.

This issue track the Port.

**Comment by tpreusse** [comment]
Do you know of any React / webpack starter kits which support Firefox and Chrome?

Currently thinking of switching this to [Create Chrome Extension](https://github.com/schovi/create-chrome-extension).

**Comment by heubergen** [comment]
Unfortunately I'm not a developer, more a advanced user so I could only read me through google and write here what I've learned.

**Comment by tpreusse** [comment]
Ok, no worries. I will look into porting as soon as possible. However we will first finish, quality assure the Chrome version and get it into the store.

**Comment by tpreusse** [comment]
I have some good news: It already runs in Firefox unmodified.

I attached a xpi file for you to test:
[lobbylayer-0.5.0-an+fx.xpi.zip](https://github.com/lobbylayer/chrome/files/752219/lobbylayer-0.5.0-an.fx.xpi.zip)

As soon as we're done with quality assurance we will release to the browser stores (approximately in a week). Thank you for raising this issue.
