### ISSUE TITLE
Icon missing on firefox

### ISSUE THREAD

**Issue by heubergen** [lobbylayer/chrome#3]
Firefox seems not to be able to use the icons anywhere.
While the icon is showed correctly on the about:addons page, it seems not to work in the toolbar:
![lobbylayer-issue2-firefox](https://cloud.githubusercontent.com/assets/5529410/22618267/1716536a-ead8-11e6-8103-ca41290ddec3.png)
Also the icon was not displayed during the installation process.

Tested with FF 54 and Win10

**Comment by tpreusse** [comment]
Here is a build with a fix: [lobbylayer-0.5.1-an+fx.xpi.zip](https://github.com/lobbylayer/chrome/files/752446/lobbylayer-0.5.1-an.fx.xpi.zip)

Thank you for reporting. Keep testing!
